services:
  auth:
    restart: always
    build:
      context: ./auth
      dockerfile: Dockerfile
    depends_on:
      - mongo_auth
      - broker
    ports:
      - 3001:3001

  mongo_auth:
    restart: always
    image: mongo:4.2.0
    volumes:
      - ./mongo/auth/data:/data/db
    expose:
      - 27017
    ports:
      - 27017:27017

  tasks:
    restart: always
    build:
      context: ./tasks
      dockerfile: Dockerfile
    depends_on:
      - mongo_tasks
      - broker
    ports:
      - 3002:3002

  mongo_tasks:
    restart: always
    image: mongo:4.2.0
    volumes:
      - ./mongo/tasks/data:/data/db
    expose:
      - 27018
    ports:
      - 27018:27018
    command: mongod --port 27018

  accounting:
    restart: always
    build:
      context: ./accounting
      dockerfile: Dockerfile
    depends_on:
      - mongo_accounting
      - broker
    ports:
      - 3003:3003

  mongo_accounting:
    restart: always
    image: mongo:4.2.0
    volumes:
      - ./mongo/accounting/data:/data/db
    expose:
      - 27019
    ports:
      - 27019:27019
    command: mongod --port 27019

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-server:7.5.0
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://broker:9092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
